stages:
  build:
    buildTool: "mta"
    buildToolVersion: "MBTJ17N18"

steps:
  mavenExecuteStaticCodeChecks: false
  npmExecuteLint: false
  tmsUpload:
    nodeName: 'TEST'
    credentialsId: 'TMS_TRAIL_Account'
    customDescription: 'Pipeline Upload to TEST Node'
