stages:
  build:
    buildTool: "mta"
    buildToolVersion: "MBTJ17N18"
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  release:
    tmsUpload: true

steps:
  tmsUpload:
    nodeName: 'TEST'
    credentialsId: 'TMS_TRAIL_Account'
    customDescription: 'Pipeline Upload to TEST Node'
