general:
  buildTool: "mta"

stages:
  build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  release:
    tmsUpload:
      nodeName: 'TEST'
      credentialsId: 'TMS_TRAIL_Account'
      customDescription: 'Pipeline Upload to TEST Node'
